### ISSUE TITLE
Manque des fichiers !

### ISSUE THREAD

**Issue by yar0d** [tskynet/vuejs_integration#1]
Le dépot devrait contenir les fichiers .eslintrc.js et .gitignore. Sans ces fichiers on a des erreurs :

```node
 ERROR  Failed to compile with 1 errors                                                                                                                                           14:51:28

Module build failed: Error: No ESLint configuration found.
    at getLocalConfig (/home/yar0d/Projects/Stéphane/vuejs_integration/node_modules/eslint/lib/config.js:162:35)
    at Config.getConfig (/home/yar0d/Projects/Stéphane/vuejs_integration/node_modules/eslint/lib/config.js:260:26)
    at processText (/home/yar0d/Projects/Stéphane/vuejs_integration/node_modules/eslint/lib/cli-engine.js:224:33)
    at CLIEngine.executeOnText (/home/yar0d/Projects/Stéphane/vuejs_integration/node_modules/eslint/lib/cli-engine.js:754:26)
    at lint (/home/yar0d/Projects/Stéphane/vuejs_integration/node_modules/eslint-loader/index.js:218:17)
    at Object.module.exports (/home/yar0d/Projects/Stéphane/vuejs_integration/node_modules/eslint-loader/index.js:213:21)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
```

Si je pose un .eslintrc.js maison, j'ai alors les erreurs :
```js
 ERROR  Failed to compile with 2 errors                                                                                                                                           15:02:43

 error  in ./node_modules/bootstrap-vue/dist/bootstrap-vue.css

Module build failed: Error: No PostCSS Config found in: /home/yar0d/Projects/Stéphane/vuejs_integration/node_modules/bootstrap-vue/dist
    at /home/yar0d/Projects/Stéphane/vuejs_integration/node_modules/postcss-load-config/index.js:51:26
    at <anonymous>

 @ ./node_modules/bootstrap-vue/dist/bootstrap-vue.css 4:14-126 13:3-17:5 14:22-134
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

 error  in ./node_modules/bootstrap/dist/css/bootstrap.css

Module build failed: Error: No PostCSS Config found in: /home/yar0d/Projects/Stéphane/vuejs_integration/node_modules/bootstrap/dist/css
    at /home/yar0d/Projects/Stéphane/vuejs_integration/node_modules/postcss-load-config/index.js:51:26
    at <anonymous>

 @ ./node_modules/bootstrap/dist/css/bootstrap.css 4:14-128 13:3-17:5 14:22-136
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
```

**Comment by tskynet** [comment]
C'est fait :)
